spring:
  datasource:
    slave:
      jdbc-url: jdbc:mysql://192.168.240.192:6000/dev_mysql_pms_data?autoReconnect=true&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver

    master:
      jdbc-url: jdbc:mysql://192.168.240.192:6000/test_pms?autoReconnect=true
      username: root
      password: 123
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mapping/*.xml
server:
  port: 8181